### ISSUE TITLE
Wrong Filename in Readme?

### ISSUE THREAD

**Issue by kitadakyou** [isayasMatter/GazeMetrics#3]
Hi.

In Configuring GazeMetrics with your scene section,
> 2. Drag the GazeMetrics prefab from your assets folder in the project panel into your scene in the hierarchy panel.

But there is no such file `GazeMetrics.prefab`. I think it should be Drag the GazeMetrics **Controller** prefab.

**Comment by isayasMatter** [comment]
Thank you for pointing this out. I have corrected it.
